/**
 * Year 1 staff scenes grouped by character.
 */

import { STAFF_ALBUS_DUMBLEDORE_YEAR1_ENCOUNTER_SCENES } from './albus-dumbledore-encounters.js';
import { STAFF_AUGUSTUS_FENWICK_YEAR1_ENCOUNTER_SCENES } from './augustus-fenwick-encounters.js';
import { STAFF_AURORA_SINISTRA_YEAR1_ENCOUNTER_SCENES } from './aurora-sinistra-encounters.js';
import { STAFF_CONSTANCE_SHACKLEBOLT_YEAR1_ENCOUNTER_SCENES } from './constance-shacklebolt-encounters.js';
import { STAFF_ELIZA_LOVEGOOD_YEAR1_ENCOUNTER_SCENES } from './eliza-lovegood-encounters.js';
import { STAFF_FELIX_WEASLEY_YEAR1_ENCOUNTER_SCENES } from './felix-weasley-encounters.js';
import { STAFF_FILIUS_FLITWICK_YEAR1_ENCOUNTER_SCENES } from './filius-flitwick-encounters.js';
import { STAFF_HERBERT_BINNS_YEAR1_ENCOUNTER_SCENES } from './herbert-binns-encounters.js';
import { STAFF_MINERVA_MC_GONAGALL_YEAR1_ENCOUNTER_SCENES } from './minerva-mc-gonagall-encounters.js';
import { STAFF_MIRANDA_PERCIVAL_YEAR1_ENCOUNTER_SCENES } from './miranda-percival-encounters.js';
import { STAFF_POMONA_SPROUT_YEAR1_ENCOUNTER_SCENES } from './pomona-sprout-encounters.js';
import { STAFF_PRIMROSE_SPROUT_YEAR1_ENCOUNTER_SCENES } from './primrose-sprout-encounters.js';
import { STAFF_REMUS_LUPIN_YEAR1_ENCOUNTER_SCENES } from './remus-lupin-encounters.js';
import { STAFF_ROLANDA_HOOCH_YEAR1_ENCOUNTER_SCENES } from './rolanda-hooch-encounters.js';
import { STAFF_SERAFINA_MOODY_YEAR1_ENCOUNTER_SCENES } from './serafina-moody-encounters.js';
import { STAFF_SEVERUS_SNAPE_YEAR1_ENCOUNTER_SCENES } from './severus-snape-encounters.js';
import { STAFF_SIRIUS_BLACK_YEAR1_ENCOUNTER_SCENES } from './sirius-black-encounters.js';
import { STAFF_SYBILL_TRELAWNEY_YEAR1_ENCOUNTER_SCENES } from './sybill-trelawney-encounters.js';
import { STAFF_TAVISH_MAC_LAREN_YEAR1_ENCOUNTER_SCENES } from './tavish-mac-laren-encounters.js';

import { STAFF_ALBUS_DUMBLEDORE_YEAR1_CHAT_SCENES } from './albus-dumbledore-chat.js';
import { STAFF_AUGUSTUS_FENWICK_YEAR1_CHAT_SCENES } from './augustus-fenwick-chat.js';
import { STAFF_AURORA_SINISTRA_YEAR1_CHAT_SCENES } from './aurora-sinistra-chat.js';
import { STAFF_CONSTANCE_SHACKLEBOLT_YEAR1_CHAT_SCENES } from './constance-shacklebolt-chat.js';
import { STAFF_ELIZA_LOVEGOOD_YEAR1_CHAT_SCENES } from './eliza-lovegood-chat.js';
import { STAFF_FELIX_WEASLEY_YEAR1_CHAT_SCENES } from './felix-weasley-chat.js';
import { STAFF_FILIUS_FLITWICK_YEAR1_CHAT_SCENES } from './filius-flitwick-chat.js';
import { STAFF_HERBERT_BINNS_YEAR1_CHAT_SCENES } from './herbert-binns-chat.js';
import { STAFF_MINERVA_MC_GONAGALL_YEAR1_CHAT_SCENES } from './minerva-mc-gonagall-chat.js';
import { STAFF_MIRANDA_PERCIVAL_YEAR1_CHAT_SCENES } from './miranda-percival-chat.js';
import { STAFF_POMONA_SPROUT_YEAR1_CHAT_SCENES } from './pomona-sprout-chat.js';
import { STAFF_PRIMROSE_SPROUT_YEAR1_CHAT_SCENES } from './primrose-sprout-chat.js';
import { STAFF_REMUS_LUPIN_YEAR1_CHAT_SCENES } from './remus-lupin-chat.js';
import { STAFF_ROLANDA_HOOCH_YEAR1_CHAT_SCENES } from './rolanda-hooch-chat.js';
import { STAFF_SERAFINA_MOODY_YEAR1_CHAT_SCENES } from './serafina-moody-chat.js';
import { STAFF_SEVERUS_SNAPE_YEAR1_CHAT_SCENES } from './severus-snape-chat.js';
import { STAFF_SIRIUS_BLACK_YEAR1_CHAT_SCENES } from './sirius-black-chat.js';
import { STAFF_SYBILL_TRELAWNEY_YEAR1_CHAT_SCENES } from './sybill-trelawney-chat.js';
import { STAFF_TAVISH_MAC_LAREN_YEAR1_CHAT_SCENES } from './tavish-mac-laren-chat.js';

export const STAFF_YEAR1_BY_CHARACTER_ENCOUNTERS = {
  ...STAFF_ALBUS_DUMBLEDORE_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_AUGUSTUS_FENWICK_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_AURORA_SINISTRA_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_CONSTANCE_SHACKLEBOLT_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_ELIZA_LOVEGOOD_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_FELIX_WEASLEY_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_FILIUS_FLITWICK_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_HERBERT_BINNS_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_MINERVA_MC_GONAGALL_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_MIRANDA_PERCIVAL_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_POMONA_SPROUT_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_PRIMROSE_SPROUT_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_REMUS_LUPIN_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_ROLANDA_HOOCH_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_SERAFINA_MOODY_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_SEVERUS_SNAPE_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_SIRIUS_BLACK_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_SYBILL_TRELAWNEY_YEAR1_ENCOUNTER_SCENES,
  ...STAFF_TAVISH_MAC_LAREN_YEAR1_ENCOUNTER_SCENES,
};

export const STAFF_YEAR1_BY_CHARACTER_CHATS = {
  ...STAFF_ALBUS_DUMBLEDORE_YEAR1_CHAT_SCENES,
  ...STAFF_AUGUSTUS_FENWICK_YEAR1_CHAT_SCENES,
  ...STAFF_AURORA_SINISTRA_YEAR1_CHAT_SCENES,
  ...STAFF_CONSTANCE_SHACKLEBOLT_YEAR1_CHAT_SCENES,
  ...STAFF_ELIZA_LOVEGOOD_YEAR1_CHAT_SCENES,
  ...STAFF_FELIX_WEASLEY_YEAR1_CHAT_SCENES,
  ...STAFF_FILIUS_FLITWICK_YEAR1_CHAT_SCENES,
  ...STAFF_HERBERT_BINNS_YEAR1_CHAT_SCENES,
  ...STAFF_MINERVA_MC_GONAGALL_YEAR1_CHAT_SCENES,
  ...STAFF_MIRANDA_PERCIVAL_YEAR1_CHAT_SCENES,
  ...STAFF_POMONA_SPROUT_YEAR1_CHAT_SCENES,
  ...STAFF_PRIMROSE_SPROUT_YEAR1_CHAT_SCENES,
  ...STAFF_REMUS_LUPIN_YEAR1_CHAT_SCENES,
  ...STAFF_ROLANDA_HOOCH_YEAR1_CHAT_SCENES,
  ...STAFF_SERAFINA_MOODY_YEAR1_CHAT_SCENES,
  ...STAFF_SEVERUS_SNAPE_YEAR1_CHAT_SCENES,
  ...STAFF_SIRIUS_BLACK_YEAR1_CHAT_SCENES,
  ...STAFF_SYBILL_TRELAWNEY_YEAR1_CHAT_SCENES,
  ...STAFF_TAVISH_MAC_LAREN_YEAR1_CHAT_SCENES,
};
