// potion-data.js
// 哈利·波特 魔药课全图鉴（含原著剧情解锁条件 + 魔药颜色）
export const potions = [
  // ==============================================
  // 一、霍格沃茨学校教授的魔药（正规课程）
  // ==============================================
  {
    id: 101,
    name: "疥疮药水",
    english: "Boil-Cure Potion",
    type: "正规课程",
    grade: "一年级",
    effect: "治疗疥疮、脓包",
    description: "成分：干荨麻、蛇牙、豪猪刺、带触角鼻涕虫，基础治疗魔药",
    materials: ["干荨麻", "蛇牙", "豪猪刺", "带触角鼻涕虫"],
    quantities: [2, 3, 2, 4],
    icon: "⚗️",
    color: "#6b8fa0",
    colorName: "蓝绿色",
    unlockCondition: "一年级魔药课自动解锁",
    unlockTip: "完成一年级第一节魔药课即可学习"
  },
  {
    id: 102,
    name: "遗忘药水",
    english: "Forgetfulness Potion",
    type: "正规课程",
    grade: "一年级",
    effect: "使人短暂失忆、健忘",
    description: "基础记忆干扰类魔药",
    materials: ["睡莲花粉", "苦艾草", "雾隐花"],
    quantities: [2, 2, 1],
    icon: "⚗️",
    color: "#a0b8d0",
    colorName: "淡蓝色",
    unlockCondition: "一年级魔药课中期解锁",
    unlockTip: "通过一年级魔药课小测验解锁"
  },
  {
    id: 103,
    name: "肿胀药水",
    english: "Swelling Solution",
    type: "正规课程",
    grade: "一年级",
    effect: "使身体部位肿胀",
    description: "基础变形/刺激类魔药",
    materials: ["膨胀苔藓", "火蜥蜴血", "蝙蝠脾脏"],
    quantities: [1, 1, 2],
    icon: "⚗️",
    color: "#c8a050",
    colorName: "黄褐色",
    unlockCondition: "一年级魔药课自动解锁",
    unlockTip: "开学即可学习的基础魔药"
  },
  {
    id: 104,
    name: "提神药剂",
    english: "Wiggenweld Potion",
    type: "正规课程",
    grade: "一年级",
    effect: "治愈轻伤、恢复精力、解除昏睡",
    description: "校医庞弗雷夫人常用基础治疗魔药",
    materials: ["薄荷芽", "甘菊", "日光花瓣"],
    quantities: [3, 2, 1],
    icon: "⚗️",
    color: "#80c8a0",
    colorName: "翠绿色",
    unlockCondition: "一年级校医室事件解锁",
    unlockTip: "首次受伤前往校医室后解锁"
  },
  {
    id: 105,
    name: "缓和药剂",
    english: "Drowsing Draught",
    type: "正规课程",
    grade: "一年级",
    effect: "助眠、镇静",
    description: "基础安眠镇静魔药",
    materials: ["罂粟籽", "薰衣草", "夜影花"],
    quantities: [2, 2, 1],
    icon: "⚗️",
    color: "#8070b0",
    colorName: "淡紫色",
    unlockCondition: "一年级期末解锁",
    unlockTip: "完成一年级期末考试解锁"
  },

  // 二～五年级 O.W.L.
  {
    id: 201,
    name: "缩身药水",
    english: "Shrinking Solution",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "缩小生物或物体",
    description: "变形类中级魔药，O.W.L. 重要考点",
    materials: ["雏菊根", "缩皱无花果", "毛毛虫", "蜘蛛毒液"],
    quantities: [2, 1, 3, 1],
    icon: "⚗️",
    color: "#90b868",
    colorName: "酸绿色",
    unlockCondition: "二年级魔药课解锁",
    unlockTip: "二年级开始学习的中级魔药"
  },
  {
    id: 202,
    name: "生发药水",
    english: "Hair-Raising Potion",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "使毛发疯狂生长、直立",
    description: "基础刺激类魔药，常用于恶作剧",
    materials: ["荨麻", "豪猪刺", "火蜥蜴血"],
    quantities: [2, 2, 1],
    icon: "⚗️",
    color: "#c89060",
    colorName: "棕褐色",
    unlockCondition: "二年级恶作剧支线解锁",
    unlockTip: "与弗雷德、乔治互动后解锁"
  },
  {
    id: 203,
    name: "镇定剂",
    english: "Draught of Peace",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "平复焦虑、镇定情绪、缓解紧张",
    description: "O.W.L. 备考常用高级镇静魔药",
    materials: ["乌头", "薄荷", "水仙根"],
    quantities: [1, 2, 2],
    icon: "⚗️",
    color: "#6088c0",
    colorName: "宁静蓝",
    unlockCondition: "三年级O.W.L.备考解锁",
    unlockTip: "开启O.W.L.考试筹备后解锁"
  },
  {
    id: 204,
    name: "复方汤剂",
    english: "Polyjuice Potion",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "变形成他人（需对方毛发），时效1小时",
    description: "极复杂、耗时21天，O.W.L. 重点、N.E.W.T. 进阶内容",
    materials: ["流液草", "草蛉虫", "蚂蟥", "目标生物毛发"],
    quantities: [3, 2, 4, 1],
    icon: "⚗️",
    color: "#6b5b3a",
    colorName: "泥浆色",
    unlockCondition: "二年级密室剧情解锁",
    unlockTip: "开启密室任务后解锁"
  },
  {
    id: 205,
    name: "增龄剂",
    english: "Aging Potion",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "增加年龄",
    description: "可用于突破年龄限制（如火焰杯）",
    materials: ["老龄苔藓", "龙血", "日光花"],
    quantities: [1, 1, 2],
    icon: "⚗️",
    color: "#a09070",
    colorName: "灰褐色",
    unlockCondition: "四年级火焰杯剧情解锁",
    unlockTip: "参与三强争霸赛年龄线事件解锁"
  },
  {
    id: 206,
    name: "补血药",
    english: "Blood-Replenishing Potion",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "快速补血、治疗失血",
    description: "中级治疗魔药",
    materials: ["红花瓣", "独角兽角粉", "石榴汁"],
    quantities: [2, 1, 3],
    icon: "⚗️",
    color: "#c04040",
    colorName: "深红色",
    unlockCondition: "四年级黑魔法制裁事件解锁",
    unlockTip: "经历战斗失血后解锁"
  },
  {
    id: 207,
    name: "欢欣剂",
    english: "Elixir to Induce Euphoria",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "使人极度开心、兴奋",
    description: "情绪调节类魔药",
    materials: ["雪滴花", "薄荷", "阳光花蜜"],
    quantities: [2, 2, 1],
    icon: "⚗️",
    color: "#f0d060",
    colorName: "阳光黄",
    unlockCondition: "五年级凤凰社剧情解锁",
    unlockTip: "加入D.A.防御协会后解锁"
  },
  {
    id: 208,
    name: "迷惑剂",
    english: "Confusing Concoction",
    type: "正规课程",
    grade: "二～五年级（O.W.L.）",
    effect: "使人混乱、判断力下降",
    description: "基础干扰类魔药",
    materials: ["混乱草", "雾隐花", "蝙蝠翅膀粉"],
    quantities: [2, 1, 2],
    icon: "⚗️",
    color: "#9090b0",
    colorName: "灰紫色",
    unlockCondition: "五年级O.W.L.考试解锁",
    unlockTip: "通过魔药O.W.L.考试后解锁"
  },

  // 六年级～N.E.W.T. 高级
  {
    id: 301,
    name: "生死水",
    english: "Draught of Living Death",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "强效昏睡，接近假死",
    description: "斯内普原创改良，哈利凭混血王子笔记成功调制",
    materials: ["缬草根", "水仙根粉末", "瞌睡豆", "乌头"],
    quantities: [2, 2, 1, 1],
    icon: "⚗️",
    color: "#404080",
    colorName: "深靛蓝色",
    unlockCondition: "六年级混血王子笔记解锁",
    unlockTip: "获得混血王子魔药课本后解锁"
  },
  {
    id: 302,
    name: "福灵剂",
    english: "Felix Felicis",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "短期大幅提升运气、规避危险",
    description: "N.E.W.T. 顶级魔药，极难调制，禁用于比赛/考试",
    materials: ["龙血", "幸运四叶草", "金盏花", "星辰花蜜"],
    quantities: [1, 2, 2, 1],
    icon: "⚗️",
    color: "#f4c542",
    colorName: "熔金",
    unlockCondition: "六年级魔药课优秀奖励解锁",
    unlockTip: "成功调制生死水获得斯拉格霍恩奖励"
  },
  {
    id: 303,
    name: "迷情剂",
    english: "Amortentia",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "产生强烈迷恋（非真爱）",
    description: "世界最强爱情魔药，气味因人而异",
    materials: ["玫瑰花瓣", "薰衣草", "珍珠粉", "月光花蜜"],
    quantities: [3, 2, 1, 1],
    icon: "⚗️",
    color: "#e8c0d0",
    colorName: "珍珠粉",
    unlockCondition: "六年级情人节剧情解锁",
    unlockTip: "参与霍格沃茨情人节活动解锁"
  },
  {
    id: 304,
    name: "吐真剂",
    english: "Veritaserum",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "强制使用者说真话",
    description: "受魔法部严格管制，魔药课高级教学内容",
    materials: ["月长石粉", "夜影花", "蛇毒"],
    quantities: [1, 2, 1],
    icon: "⚗️",
    color: "#d0e8f0",
    colorName: "无色透明",
    unlockCondition: "魔法部权限解锁",
    unlockTip: "完成魔法部相关任务后解锁"
  },
  {
    id: 305,
    name: "狼毒药剂",
    english: "Wolfsbane Potion",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "狼人满月时保持理智、不伤人",
    description: "斯内普为卢平特制，高级治疗魔药",
    materials: ["乌头", "狼毒草", "银粉", "月光露水"],
    quantities: [2, 2, 1, 3],
    icon: "⚗️",
    color: "#5080b0",
    colorName: "蓝银色",
    unlockCondition: "三年级卢平支线解锁",
    unlockTip: "帮助卢平教授度过满月后解锁"
  },
  {
    id: 306,
    name: "强效提神药剂",
    english: "Wiggenweld Potion (Strong)",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "治愈重伤、快速恢复体力、解除诅咒影响",
    description: "提神药剂的高级强化版本",
    materials: ["甘菊", "日光花瓣", "独角兽角粉", "白鲜"],
    quantities: [3, 2, 1, 1],
    icon: "⚗️",
    color: "#40c870",
    colorName: "鲜绿色",
    unlockCondition: "六年级N.E.W.T.课程解锁",
    unlockTip: "进入高级魔药班自动解锁"
  },
  {
    id: 307,
    name: "通用解毒剂",
    english: "Universal Antidote",
    type: "正规课程",
    grade: "六年级～N.E.W.T. 高级",
    effect: "解除普通毒药、咬伤",
    description: "含粪石（羊胃结石，万能解毒），高级魔药教学内容",
    materials: ["粪石", "薄荷", "水仙根", "蒲公英"],
    quantities: [1, 2, 2, 3],
    icon: "⚗️",
    color: "#80a880",
    colorName: "灰绿色",
    unlockCondition: "五年级禁林事件解锁",
    unlockTip: "获得马人信任或获得粪石后解锁"
  },

  // 治疗/辅助
  {
    id: 401,
    name: "白鲜香精",
    english: "Essence of Dittany",
    type: "正规课程",
    grade: "治疗/辅助",
    effect: "治愈伤口、止血、防止感染",
    description: "巫师治疗必备魔药",
    materials: ["白鲜花瓣", "露水", "甘菊"],
    quantities: [2, 3, 1],
    icon: "⚗️",
    color: "#b0d0c0",
    colorName: "淡绿",
    unlockCondition: "六年级神锋无影剧情解锁",
    unlockTip: "哈利使用神锋无影受伤后解锁"
  },
  {
    id: 402,
    name: "曼德拉草复活药剂",
    english: "Mandrake Restorative Draught",
    type: "正规课程",
    grade: "治疗/辅助",
    effect: "解除石化效果",
    description: "草药学与魔药学结合课程，密室事件中使用",
    materials: ["曼德拉草", "水仙根", "薄荷", "月光露水"],
    quantities: [1, 2, 2, 3],
    icon: "⚗️",
    color: "#a0b878",
    colorName: "草绿色",
    unlockCondition: "二年级密室剧情解锁",
    unlockTip: "启动石化解救任务后解锁"
  },
  {
    id: 403,
    name: "愈合药剂",
    english: "Healing Potion",
    type: "正规课程",
    grade: "治疗/辅助",
    effect: "加速伤口愈合、接骨",
    description: "常用治疗魔药",
    materials: ["白鲜", "甘菊", "蒲公英根"],
    quantities: [2, 2, 3],
    icon: "⚗️",
    color: "#c8b880",
    colorName: "暖金色",
    unlockCondition: "校医室常驻解锁",
    unlockTip: "基础治疗魔药，一年级后期解锁"
  },

  // ==============================================
  // 二、其他途径（非学校正规教学）
  // ==============================================

  // 黑魔法/禁药
  {
    id: 501,
    name: "极致生死水",
    english: "Draught of Living Death (Ultimate)",
    type: "非课程",
    grade: "黑魔法/禁药",
    effect: "永久沉睡、致死",
    description: "禁术级魔药，非霍格沃茨教学内容",
    materials: ["死神草", "夜影花", "剧毒蘑菇", "蛇毒"],
    quantities: [2, 2, 1, 1],
    icon: "💀",
    color: "#1a0a20",
    colorName: "黑紫色",
    unlockCondition: "黑魔法路线解锁",
    unlockTip: "触碰黑魔法道具/禁书区解锁"
  },
  {
    id: 502,
    name: "魂器守护剧毒",
    english: "Horcrux Guardian Poison",
    type: "非课程",
    grade: "黑魔法/禁药",
    effect: "剧毒，无常规解药",
    description: "伏地魔自制，用于保护魂器，仅凤凰眼泪可解",
    materials: ["黑魔法草", "龙毒", "暗影花", "夜影花"],
    quantities: [1, 1, 2, 2],
    icon: "💀",
    color: "#204020",
    colorName: "深绿",
    unlockCondition: "魂器任务解锁",
    unlockTip: "寻找魂器时遭遇剧毒陷阱解锁"
  },
  {
    id: 503,
    name: "黑暗狼毒药剂",
    english: "Dark Wolfsbane Potion",
    type: "非课程",
    grade: "黑魔法/禁药",
    effect: "强化狼人狂暴、失去理智",
    description: "食死徒改造版本，非正规魔药",
    materials: ["黑乌头", "狼毒草", "暗影粉", "蝙蝠血"],
    quantities: [2, 2, 1, 1],
    icon: "💀",
    color: "#602020",
    colorName: "暗血红",
    unlockCondition: "食死徒剧情解锁",
    unlockTip: "遭遇狼人食死徒后解锁"
  },
  {
    id: 504,
    name: "特制杀人毒药",
    english: "Custom Killing Poisons",
    type: "非课程",
    grade: "黑魔法/禁药",
    effect: "快速致命",
    description: "黑市/禁书/伏地魔专属，非课程内容",
    materials: ["剧毒蘑菇", "蛇毒", "夜影花", "死神草"],
    quantities: [1, 1, 2, 1],
    icon: "💀",
    color: "#306030",
    colorName: "毒液绿",
    unlockCondition: "黑市交易解锁",
    unlockTip: "进入对角巷黑市区域解锁"
  },
  {
    id: 505,
    name: "诅咒药剂",
    english: "Cursing Potions",
    type: "非课程",
    grade: "黑魔法/禁药",
    effect: "施加长期恶咒、痛苦、变形诅咒",
    description: "禁术级黑魔法魔药",
    materials: ["暗影花", "诅咒苔藓", "黑乌头", "蝙蝠翅膀"],
    quantities: [2, 2, 1, 2],
    icon: "💀",
    color: "#281828",
    colorName: "暗紫",
    unlockCondition: "禁书区黑暗魔法解锁",
    unlockTip: "在禁书区阅读黑暗典籍后解锁"
  },

  // 自学/禁书/私人配方
  {
    id: 601,
    name: "神锋无影魔药",
    english: "Sectumsempra Potion",
    type: "非课程",
    grade: "自学/私人配方",
    effect: "配合神锋无影咒造成深割伤、难愈合",
    description: "斯内普（混血王子）原创，非教学内容",
    materials: ["锋利草", "龙血", "暗影粉", "夜影花"],
    quantities: [2, 1, 1, 1],
    icon: "🖤",
    color: "#401010",
    colorName: "深红",
    unlockCondition: "混血王子笔记专属解锁",
    unlockTip: "阅读混血王子课本黑暗咒术篇解锁"
  },
  {
    id: 602,
    name: "改良生死水",
    english: "Draught of Living Death (Improved)",
    type: "非课程",
    grade: "自学/私人配方",
    effect: "强效昏睡，调制难度大幅降低",
    description: "混血王子笔记独家改良版",
    materials: ["瞌睡豆", "水仙根粉末", "缬草根", "银粉"],
    quantities: [1, 2, 2, 1],
    icon: "🖤",
    color: "#383868",
    colorName: "深蓝",
    unlockCondition: "混血王子笔记解锁",
    unlockTip: "掌握混血王子改良技巧后解锁"
  },
  {
    id: 603,
    name: "无痕伸展咒配套魔药",
    english: "Undetectable Extension Charm Potion",
    type: "非课程",
    grade: "自学/私人配方",
    effect: "扩大空间容量",
    description: "用于魔法道具，家族自学/禁书内容",
    materials: ["空间草", "月光花蜜", "星辰粉"],
    quantities: [2, 1, 1],
    icon: "✨",
    color: "#8090c0",
    colorName: "浅蓝",
    unlockCondition: "家族魔法支线解锁",
    unlockTip: "获得无痕伸展道具后解锁"
  },
  {
    id: 604,
    name: "韦斯莱恶作剧魔药",
    english: "Weasley's Wizard Wheezes Potions",
    type: "非课程",
    grade: "自学/私人配方",
    effect: "逃课、呕吐、流鼻血等恶作剧效果",
    description: "弗雷德、乔治自制，非课程内容",
    materials: ["喷嚏草", "呕吐豆", "鼻血花", "气泡草"],
    quantities: [2, 2, 1, 3],
    icon: "😜",
    color: "#e88030",
    colorName: "亮橙色",
    unlockCondition: "韦斯莱魔法把戏坊解锁",
    unlockTip: "对角巷开店后购买配方解锁"
  },
  {
    id: 605,
    name: "快速复方汤剂",
    english: "Quick Polyjuice Potion",
    type: "非课程",
    grade: "自学/私人配方",
    effect: "快速变形，时效缩短",
    description: "民间/黑市改良版，非学校标准配方",
    materials: ["流液草", "蚂蟥", "目标毛发", "闪电花"],
    quantities: [2, 2, 1, 1],
    icon: "✨",
    color: "#5a4a2a",
    colorName: "深棕",
    unlockCondition: "黑市魔法解锁",
    unlockTip: "黑市购买快速调制秘方解锁"
  },
  {
    id: 606,
    name: "牢不可破誓言辅助魔药",
    english: "Unbreakable Vow Potion",
    type: "非课程",
    grade: "古老魔法",
    effect: "辅助牢不可破誓言仪式",
    description: "非霍格沃茨教学体系",
    materials: ["誓言草", "龙血", "银粉"],
    quantities: [1, 1, 2],
    icon: "🔒",
    color: "#c0a030",
    colorName: "暗金",
    unlockCondition: "古老魔法仪式解锁",
    unlockTip: "参与牢不可破誓言仪式后解锁"
  },

  // 特殊/古老/黑市
  {
    id: 701,
    name: "凤凰泪药剂",
    english: "Phoenix Tear Potion",
    type: "非课程",
    grade: "特殊/稀有",
    effect: "解一切毒、治愈致命伤",
    description: "非教学，极度稀有",
    materials: ["凤凰泪", "白鲜", "星辰花蜜"],
    quantities: [1, 2, 1],
    icon: "🐦",
    color: "#ff8040",
    colorName: "金红色",
    unlockCondition: "凤凰羁绊解锁",
    unlockTip: "获得凤凰信任/获得凤凰泪后解锁"
  },
  {
    id: 702,
    name: "门钥匙魔药",
    english: "Portus Potion",
    type: "非课程",
    grade: "特殊/古老",
    effect: "制作门钥匙",
    description: "高级定制魔药，非基础咒语",
    materials: ["传送草", "月光露水", "星辰粉"],
    quantities: [2, 2, 1],
    icon: "🌀",
    color: "#6090c0",
    colorName: "天蓝",
    unlockCondition: "门钥匙事件解锁",
    unlockTip: "通过门钥匙传送后解锁"
  },
  {
    id: 703,
    name: "赤胆忠心咒辅助魔药",
    english: "Fidelius Charm Potion",
    type: "非课程",
    grade: "特殊/古老",
    effect: "强化秘密隐藏效果",
    description: "古老魔法，非课程内容",
    materials: ["秘密草", "银粉", "月光花蜜"],
    quantities: [2, 1, 1],
    icon: "🔒",
    color: "#c0c0d0",
    colorName: "银白",
    unlockCondition: "赤胆忠心咒剧情解锁",
    unlockTip: "参与赤胆忠心咒守护任务解锁"
  },
  {
    id: 704,
    name: "幻身药剂",
    english: "Disillusionment Potion",
    type: "非课程",
    grade: "特殊/黑市",
    effect: "完全隐形，效果强于幻身咒",
    description: "自学/禁书内容",
    materials: ["隐形苔藓", "雾隐花", "月光露水"],
    quantities: [2, 1, 3],
    icon: "👤",
    color: "#a0a0b0",
    colorName: "半透明银灰",
    unlockCondition: "隐形任务解锁",
    unlockTip: "需要潜行任务时自动解锁"
  },
  {
    id: 705,
    name: "烈火熊熊强化魔药",
    english: "Fiendfyre Potion",
    type: "非课程",
    grade: "黑魔法/禁术",
    effect: "强化魔焰、控制方向",
    description: "禁术级古老黑魔法",
    materials: ["火焰花", "龙血", "暗影粉"],
    quantities: [2, 1, 1],
    icon: "🔥",
    color: "#ff3000",
    colorName: "烈焰红",
    unlockCondition: "厉火禁术解锁",
    unlockTip: "接触厉火魔法后解锁"
  },

  // 其他特殊魔药
  {
    id: 801,
    name: "胡话饮料",
    english: "Babbling Beverage",
    type: "非课程",
    grade: "其他特殊",
    effect: "使人胡言乱语",
    description: "斯内普提及，非教学内容",
    materials: ["胡话草", "雾隐花", "蜂蜜水"],
    quantities: [2, 1, 2],
    icon: "🗣️",
    color: "#c8c050",
    colorName: "黄色",
    unlockCondition: "恶作剧支线解锁",
    unlockTip: "完成校园恶作剧任务解锁"
  },
  {
    id: 802,
    name: "美丽药剂",
    english: "Beautifying Potion",
    type: "非课程",
    grade: "其他特殊",
    effect: "美化外表",
    description: "民间/商店售卖，非课程",
    materials: ["玫瑰花瓣", "珍珠粉", "花蜜"],
    quantities: [3, 1, 2],
    icon: "💅",
    color: "#f0c8d8",
    colorName: "粉红",
    unlockCondition: "霍格莫德商店解锁",
    unlockTip: "在蜂蜜公爵/佐科店铺购买解锁"
  },
  {
    id: 803,
    name: "直发烫发剂",
    english: "Sleekeazy's Hair Potion",
    type: "非课程",
    grade: "其他特殊",
    effect: "柔顺、定型头发",
    description: "哈利祖父发明，赫敏舞会使用，商业/家族配方",
    materials: ["柔顺草", "花蜜", "月光露水"],
    quantities: [2, 2, 1],
    icon: "💇",
    color: "#e8e0c8",
    colorName: "奶油色",
    unlockCondition: "圣诞舞会剧情解锁",
    unlockTip: "参与圣诞舞会准备任务解锁"
  }
];

// 导出分类，方便前端筛选
export const potionTypes = [
  { label: "正规课程", value: "正规课程" },
  { label: "非课程", value: "非课程" }
];

export const potionGrades = [
  { label: "一年级", value: "一年级" },
  { label: "二～五年级（O.W.L.）", value: "二～五年级（O.W.L.）" },
  { label: "六年级～N.E.W.T. 高级", value: "六年级～N.E.W.T. 高级" },
  { label: "治疗/辅助", value: "治疗/辅助" },
  { label: "黑魔法/禁药", value: "黑魔法/禁药" },
  { label: "自学/私人配方", value: "自学/私人配方" },
  { label: "特殊/古老", value: "特殊/古老" },
  { label: "其他特殊", value: "其他特殊" }
];

export function getPotionEmoji(name) {
  const found = potions.find(p => p.name === name);
  return found?.icon || "🧪";
}

// ============================================================
// 材料处理映射表
// ============================================================
export const materialProcessingMap = {
  "缬草根": { action: "cut", resultName: "切割好的缬草根", icon: "🌿✂️", processVerb: "切割" },
  "曼德拉草": { action: "cut", resultName: "切碎的曼德拉草", icon: "🌱✂️", processVerb: "切割" },
  "雏菊根": { action: "cut", resultName: "切片的雏菊根", icon: "🌼✂️", processVerb: "切割" },
  "白鲜": { action: "cut", resultName: "切碎的白鲜", icon: "🌿✂️", processVerb: "切割" },
  "锋利草": { action: "cut", resultName: "切割的锋利草", icon: "🌿✂️", processVerb: "切割" },
  "流液草": { action: "cut", resultName: "切碎的流液草", icon: "🌿✂️", processVerb: "切割" },

  "瞌睡豆": { action: "crush", resultName: "压碎的瞌睡豆", icon: "🫘✨", processVerb: "压碎" },
  "蛇牙": { action: "crush", resultName: "蛇牙粉末", icon: "🦷✨", processVerb: "压碎" },
  "月长石": { action: "crush", resultName: "月长石粉末", icon: "🌙✨", processVerb: "压碎" },
  "独角兽角": { action: "crush", resultName: "独角兽角粉", icon: "🦄✨", processVerb: "压碎" },
  "水仙根": { action: "crush", resultName: "水仙根粉末", icon: "🌸✨", processVerb: "压碎" },
  "珍珠": { action: "crush", resultName: "珍珠粉", icon: "🦪✨", processVerb: "压碎" },
  "星辰石": { action: "crush", resultName: "星辰粉", icon: "⭐✨", processVerb: "压碎" },
  "银石": { action: "crush", resultName: "银粉", icon: "🥈✨", processVerb: "压碎" },
  "豪猪刺": { action: "crush", resultName: "豪猪刺粉末", icon: "🦔✨", processVerb: "压碎" },
  "粪石": { action: "crush", resultName: "粪石粉末", icon: "🪨✨", processVerb: "压碎" },

  "草蛉虫": { action: "juice", resultName: "草蛉虫汁液", icon: "🪲💧", processVerb: "榨汁" },
  "火蜥蜴": { action: "juice", resultName: "火蜥蜴血液", icon: "🦎💧", processVerb: "榨汁" },
  "蝙蝠脾脏": { action: "juice", resultName: "蝙蝠脾脏汁", icon: "🦇💧", processVerb: "榨汁" },
  "雾隐花": { action: "juice", resultName: "雾隐花精华", icon: "🌫️💧", processVerb: "榨汁" },
  "阳光花": { action: "juice", resultName: "阳光花蜜", icon: "🌞💧", processVerb: "榨汁" },
  "月光花": { action: "juice", resultName: "月光花蜜", icon: "🌙💧", processVerb: "榨汁" },
  "石榴": { action: "juice", resultName: "石榴汁", icon: "🍎💧", processVerb: "榨汁" },
  "带触角鼻涕虫": { action: "juice", resultName: "鼻涕虫黏液", icon: "🐛💧", processVerb: "榨汁" },
  "蚂蟥": { action: "juice", resultName: "蚂蟥汁", icon: "🪱💧", processVerb: "榨汁" }
};

window.getPotionEmoji = getPotionEmoji;