name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create zip
        run: |
          zip -r "${{ steps.get_version.outputs.VERSION }}.zip" . -x ".git/*" ".github/*"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.get_version.outputs.VERSION }}.zip
          generate_release_notes: true